export { Home } from './home';
export { AboutUs } from './about-us';
export { Contact } from './contact';
export { FAQ } from './faq';
export { Process } from './process';
export { LectureCompanies } from './lecture-companies';
export { GmbH } from './gmbh';
export { UG } from './ug';
export { Impressum } from './impressum';
